name: Docs CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Rodar markdownlint em todos os arquivos .md
        run: markdownlint '**/*.md'
